### ISSUE TITLE
运行不了，还缺少一个 Logger类库

### ISSUE THREAD

**Issue by jiangfeng0103** [VeroFess/QQBot#8]
![2018-10-15_144141](https://user-images.githubusercontent.com/12807989/46933931-95134d80-d088-11e8-984d-a7b8a51e8bc1.png)

**Comment by maozhenyu123** [comment]
为什么感觉这里面根本没有核心类库的呢

**Comment by VeroFess** [comment]
旧版以废弃,请等待新版更新
